version: '3'

services:
  aerospike:
    image: aerospike/aerospike-server:latest
    container_name: aerospike
    ports:
      - "3000:3000"  # Service port
      - "3001:3001"  # Fabric port
      - "3003:3003"  # Info port
    volumes:
      - ./aerospike/aerospike.conf:/etc/aerospike/aerospike.template.conf:ro
      - ./aerospike/data:/opt/aerospike/data
    restart: unless-stopped
    networks:
      - aerospike-network

  amc:
    image: aerospike/amc:latest
    container_name: aerospike-amc
    ports:
      - "8081:8081"  # AMC web UI
    restart: unless-stopped
    depends_on:
      - aerospike
    networks:
      - aerospike-network
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/zoneinfo:/usr/share/zoneinfo:ro

networks:
  aerospike-network:
    driver: bridge
